version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "root"
      MYSQL_DATABASE: "devops"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysqldb
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/devops?useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"

      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL5InnoDBDialect"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    volumes:
      - .m2:/root/.m2

volumes:
  db_data:
