version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "root"
      MYSQL_DATABASE: "devops"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysqldb
    restart: always
    environment:
        - SPRING_DATASOURCE_URL= jdbc:mysql://mysqldb:3306/devops?useSSL=false&allowPublicKeyRetrieval=true
        - SPRING_DATASOURCE_USERNAME = root
        - SPRING_DATASOURCE_PASSWORD = 123456
        - SPRING_JPA_HIBERNATE_DDL_AUTO= update
        - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT= org.hibernate.dialect.MySQL8Dialect
        - ALLOW_PUBLIC_KEY_RETRIEVAL= true
        - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE= "*"
        - MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS= ALWAYS
        - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED= true

    volumes:
      - .m2:/root/.m2

    ports:
      - 8082:8082


volumes:
  db_data:
